### ISSUE TITLE
Compatibility changes for latest Angel's version

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/SeaBlock#210]
- [x] Remove Blue Science prerequisite from Blue Algae processing
- [x] Remove additions of missing science pack prerequisite that have now been implemented in Angels
  - Logistics
    - bio-fermentation
    - bio-nutrient-paste
    - bio-paper-2
    - angels-metallurgy-2
    - pressure-tanks
  - Chemical
    - thermal-water-extraction-2
    - bio-plastic-2
    - slag-processing-2
    - angels-advanced-gas-processing
    - angels-advanced-oil-processing
    - bio-paper-3
    - gas-steam-cracking-2
    - oil-steam-cracking-2
    - ore-leaching
    - bio-arboretum-desert-3
    - bio-arboretum-swamp-3
    - bio-arboretum-temperate-3
    - angels-metallurgy-3
  - Military
    - angels-explosives-1
  - Production
    - angels-metallurgy-4
  - Utility
    - angels-metallurgy-5
- [x] Remove temp fix for double Glowing hot iron plate #195
- [x] Add prerequisite Powder refining to Advanced ore refining 2 (for new fluorite ore catalyst sorting recipe)
- [x] Hide new pollution modifier setting
- [x] Use updated graphics for Ore Sorting Facility 5
- [x] Remove bio token changes https://github.com/Arch666Angel/mods/issues/720
- [x] Remove adding blue science prerequisite to Chlorine processing 3 and Sulfur processing 4
- [x] ~~Update Chlorine processing 4 tech to use new icon function~~
- [x] Remove setting crafting category for fibreglass boards
- [x] Remove Sodium Perchlorate changes #218 
- [x] Remove reducing Heat Exchanger tech tier #233 
- [x] Remove adding yellow metal catalyst to dinitrogen tetroxide https://github.com/Arch666Angel/mods/issues/692
- [x] Remove removing bob's electrolysis tech prerequisites
- [x] Hide recipe Lithia Salt > Thermal Water
- [x] Remove Coal Processing as a prerequisite for Manganese 1
